project361/expertFinder/urls.py
from django.urls import path
from . import views

app_name = "expertFinder"

urlpatterns = [
    path("", views.index, name="editUserForm"),
    path("<int:pk>/", views.display_expert, name="display_expert"),
    path("search_results", views.search_results, name='search_results'),
]
handler400 = 'expertFinder.error_handlers.bad_request'

project361/project361/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("expertFinder.urls")),

]

project361/expertFinder/models.py
from django.db import models
from django.forms import ModelForm
from django.views.generic import ListView


# the great expert finder model!
class Expert(models.Model):
    firstName = models.CharField(max_length=55)
    lastName = models.CharField(max_length=55)
    organization = models.CharField(max_length=100)
    techSkills = models.TextField()
    courseWork = models.TextField()
    gitRepo = models.URLField()
    linkedIn = models.URLField()
    twitter = models.URLField()
    email = models.EmailField()

    def __str__(self):
        return self.lastName

project361/expertFinder/forms.py
from django import forms
from django.forms import modelformset_factory, ModelForm
from .models import Expert

DROP_DOWN_CHOICES = [
    ('name', 'Last Name'),
    ('skill', 'Skill'),
    ('class', 'Class'),
    ('organization', 'Organization')
]


class search_drop_down(forms.Form):
    search_by = forms.CharField(label='Search By', widget=forms.Select(choices=DROP_DOWN_CHOICES))
    search_term = forms.CharField(max_length=100)


expert_name_list = modelformset_factory(Expert, fields=('firstName', 'lastName', 'id'))

project361/expertFinder/views.py
from django.shortcuts import render
from .models import Expert
from .forms import search_drop_down
from django.views.generic import ListView


def edit_profile(request):
    if request.method == "POST":
        form = edit_profile(request.POST)
        if form.is_valid():
            form.save()
        else:
            form = edit_profile(request)
            return render(request, 'editexpert.html', {'form': form})

def index(request):
    search = search_drop_down()
    return render(request, "search.html", {
            "form": search
        })

def display_expert(request, pk):
    # pk is search string, want to search by last name (for now)
    print(pk)
    expert = Expert.objects.get(pk=pk)
    print(expert)
    results = {
        'expert': expert
    }
    return render(request, "display_expert.html", results)

def search_results(request):
    search_for = request.GET
    print(search_for)
    print(request.POST)
    # POST returns dict value, need to search db by type for value specified, then
    # iterate through results, putting first+lastName into listbox and record ID

    form = None
    if search_for['search_by'] == 'name':
        query_results = Expert.objects.all().filter(lastName__contains=search_for['search_term'])
    if search_for['search_by'] == 'skill':
        query_results = Expert.objects.all().filter(techSkills__contains=search_for['search_term'])
    if search_for['search_by'] == 'class':
        query_results = Expert.objects.all().filter(courseWork__contains=search_for['search_term'])
    if search_for['search_by'] == 'organization':
        query_results = Expert.objects.all().filter(organization__contains=search_for['search_term'])

    # TODO handle no results, probaby in search_results.html body
    results = {
        'query': query_results
    }
    print(results)
    return render(request, "search_results.html", results)

project361/expertFinder/templates/display_expert.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
{{expert.lastName}}
{% endblock %}

{% block body %}
    <h1>View Expert</h1>

    <ul>
       <div class="card mb-2">
           <p class="card-text">{{ expert.firstName }}</p>
           <p class="card-text">{{ expert.lastName }}</p>
           <p class="card-text">{{ expert.organization }}</p>
           <p class="card-text">{{ expert.techSkills }}</p>
           <p class="card-text">{{ expert.courseWork }}</p>
           <p class="card-text">{{ expert.gitRepo }}</p>
           <p class="card-text">{{ expert.linkedIn }}</p>
           <p class="card-text">{{ expert.twitter }}</p>
           <p class="card-text">{{ expert.email }}</p>
       </div>
    </ul>

{% endblock %}

project361/expertFinder/templates/editexpert.html
{% extends "layout.html" %}

{% block title %}
    Edit Expert
{% endblock %}

{% block body %}
    <h1>Edit Expert</h1>

    <ul>
       <div class="container">
            <form method="POST">
              <fieldset>
                <legend>Form</legend>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
              </fieldset>
            </form>
        </div>
    </ul>

{% endblock %}

project361/expertFinder/templates/expertFinder/expert_form.html
{% extends "layout.html" %}

{% block title %}
    Add Expert
{% endblock %}

{% block body %}
    <h1>Add Expert</h1>

    <ul>
       <div class="card mb-2">
            <form method="POST">


                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary"></input>

            </form>
        </div>
    </ul>

{% endblock %}

project361/expertFinder/templates/expert_form.html
{% extends "layout.html" %}

{% block title %}
    Add Expert
{% endblock %}

{% block body %}
    <h1>Edit Expert</h1>

    <ul>
       <div class="card mb-2">
            <form method="POST">


                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary">Save</input>

            </form>
        </div>
    </ul>

{% endblock %}

project361/expertFinder/templates/layout.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Nav Placeholder</h2>
                <div>
                    Search
                </div>
                <div>
                    Edit
                </div>
                <div>
                    Something
                </div>
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project361/expertFinder/templates/search.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
Find Expert
{% endblock %}

{% block body %}
    <h1>Find Expert</h1>

    <ul>
        <form action="{% url 'expertFinder:search_results' %}" method="POST" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Search</button>
        </form>
    </ul>

{% endblock %}

project361/expertFinder/templates/search_results.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
Search Results
{% endblock %}

{% block body %}
    <h1>Find Expert</h1>

    <ul>
        {% for expert in query %}
        <form  action="{% url 'expertFinder:display_expert' expert.id %}" method="POST" class="post-form">
            {% csrf_token %}

            <div class="card mb-2">
               <p class="card-text">{{ expert.firstName }}</p>
               <p class="card-text">{{ expert.lastName }}</p>
               <p class="card-text">{{ expert.organization }}</p>
               <p class="card-text">{{ expert.techSkills }}</p>
               <p class="card-text">{{ expert.courseWork }}</p>
               <p class="card-text">{{ expert.gitRepo }}</p>
               <p class="card-text">{{ expert.linkedIn }}</p>
               <p class="card-text">{{ expert.twitter }}</p>
               <p class="card-text">{{ expert.email }}</p>
                <br>
            <button  type="submit" class="save btn btn-default">Go to Expert</button>
            </div>
            </form>


        {% endfor %}
    </ul>

{% endblock %}